### ISSUE TITLE
When to release the code and the pretrained model?

### ISSUE THREAD

**Issue by Frost24K** [amaralibey/Bag-of-Queries#1]
Hi, thank you for sharing this interesting work, the idea and benchmark scores are impressive in the paper.
Could you please let us know when the code and pre-trained models will be open-sourced?  

Best regards

**Comment by STSTERANDMOMO** [comment]
> Hi, thank you for sharing this interesting work, the idea and benchmark scores are impressive in the paper. Could you please let us know when the code and pre-trained models will be open-sourced?
> 
> Best regards

A few years later.

**Comment by amaralibey** [comment]
Hello @Frost24K,

The code and weights have been released. More weights will soon be added. If you want to train the model, you can use GSV-Cities framework (https://github.com/amaralibey/gsv-cities). Also, we will publish a new framework for training, prototyping and evaluation.
You can click on "watch" if you want to reveive updates :) (and star the repo if you liked it ;D

Best regards,
Amar
