### ISSUE TITLE
impact of batch size

### ISSUE THREAD

**Issue by sumitmishra209** [amaralibey/Bag-of-Queries#13]
Hi @amaralibey  have you tried to train BOQ with small batch sizes like 32, mainly restrication due to 24 GB GPU?
I tried but was not able to reach the accuracy as reported. Also although the MSLS val ACC I got around 92.43 but for Nordland, it is worst hardly around 69. Also for SPED the ACC is 87 something.
If possible can you put your view on what could be happening and suggest how it can be improved. Thanks!

**Comment by amaralibey** [comment]
Hello @sumitmishra209 

You can actually train BoQ (with DinoV2 backbone) with batch size of 160x4 (160 places, each with 4 images). You only need to use image size of 224x224 during training, and 322x322 during test. Just make sure you're using mixed-precision training (`precision="16-mixed"` in the run.py file), to save memory and time.
