### ISSUE TITLE
Help Needed to Regenerate Attention Heatmaps for VPR Project

### ISSUE THREAD

**Issue by akselpoulsen** [amaralibey/Bag-of-Queries#15]
Hello! I'm working on a Visual Place Recognition (VPR) project at Aalborg University, and I'm trying to replicate the attention heatmaps you've shared to visualize query attentions. Unfortunately, I've been unable to achieve the same results. Would you be able to provide the code or share any insights on how you generated the attention heatmaps?

**Comment by amaralibey** [comment]
Hello @akselpoulsen 

I have just added a notebook that illustrates how to visualize the attention maps of BoQ.

Thank you for your interest.
