### ISSUE TITLE
Can you share the following msls-challenge data set?Thank you very much

### ISSUE THREAD

**Issue by lv162** [amaralibey/Bag-of-Queries#17]

**Comment by amaralibey** [comment]
Hello @lv162 

The MSLS-Challenge is the test set of the Mapillary-SLS dataset. You can find instructions on how to download the dataset on their GitHub repository: https://github.com/mapillary/mapillary_sls

They also provide a demo notebook to demonstrate how to generate the test output file. This file can be uploaded to their benchmarking platform to evaluate your performance.

- demo: https://github.com/mapillary/mapillary_sls/blob/main/demo.ipynb
- Benchmarking platform: https://codalab.lisn.upsaclay.fr/competitions/865
