### ISSUE TITLE
Your research results are impressive! I'm curious about how to implement the "learned Bag of Queries" mentioned in the paper. After reading the paper, it seems to be related to the size of the batch_size. How can the reproducibility of the results be ensured? I hope you can publish your code soon, as I am very interested! Thank you!

### ISSUE THREAD

**Issue by STSTERANDMOMO** [amaralibey/Bag-of-Queries#2]

**Comment by amaralibey** [comment]
Hello @STSTERANDMOMO,

Thank you for your interest,

The code and weights have just been released. More weights will be available soon. For the training, you can either use GSV-Cities framework (https://github.com/amaralibey/gsv-cities) or wait for our new framework in the coming weeks. Please give the repos a star, and "watch" if you want to receive new updates.

Best regards,
Amar
