### ISSUE TITLE
Nordland*

### ISSUE THREAD

**Issue by LKELN** [amaralibey/Bag-of-Queries#4]
Hello, can you provide information on how to download Nordland*?

**Comment by amaralibey** [comment]
Hello @LKELN 

I have provided info on how to download Nordland* (the 1 frame threshold) in our GSV-Cities repo: https://github.com/amaralibey/gsv-cities/blob/main/notebooks/evaluate_model.ipynb

Other benchmarks (including a different split of Nordland, the 10 frames threshold) can be foud on Gabriele's repo here: https://github.com/gmberton/VPR-datasets-downloader

**Comment by LKELN** [comment]
Thanks!
